### ISSUE TITLE
Off-mesh connection links not removed between layers in the same tile location

### ISSUE THREAD

**Issue by Sandern** [recastnavigation/recastnavigation#113]
I've been running into some crashes during path finding and after some digging I found some of my tiles ended up with invalid links. This happens when neighboring tiles in the same layer were rebuild, but only for tiles with off-mesh connections between them.

Looking in unconnectExtLinks I found the following check:
```
			if (tile->links[j].side != 0xff &&
				decodePolyIdTile(tile->links[j].ref) == targetNum)
```

side only seems to be set to 0xff when off-mesh connections are created between tiles in the same layer.

It seems neighboring tiles in the same layer are skipped when removing links. Is there any reason for doing so? I removed the check from my code and don't see any side effects.

**Comment by Janiels** [comment]
I think the check can indeed be removed without any side effects - it was based on the assumption that all external links would have `side != 0xff`. However, after layers were introduced, I think this is no longer the case.
On the other hand it suffices to check that the link reference is to the target tile, as this will be true for external links only. I'm just not sure why the problem only occurs with off-mesh connections, and not regular external links between layers (for example due to stairs).

@memononen can you confirm if my understanding is correct?

**Comment by memononen** [comment]
I think the check is valid, 0xff == this tile. The problem could potentially be also in `connectExtOffMeshLinks`. I recommend to double check all the `side == -1` cases, those cases should connect off-mesh links between layers inside same tile location.

**Comment by Janiels** [comment]
Indeed, the off-mesh links between layers are connected with `side = 0xff` from [here](https://github.com/recastnavigation/recastnavigation/blob/6285b17587bf06d2d71a32df74e22e1d18da93fc/Detour/Source/DetourNavMesh.cpp#L496) (`connectExtOffMeshLinks` is called with `side = -1` from [here](https://github.com/recastnavigation/recastnavigation/blob/6285b17587bf06d2d71a32df74e22e1d18da93fc/Detour/Source/DetourNavMesh.cpp#L958)). However, there is no similar mechanism in `removeTile` to remove these links again. The external links are removed [here](https://github.com/recastnavigation/recastnavigation/blob/6285b17587bf06d2d71a32df74e22e1d18da93fc/Detour/Source/DetourNavMesh.cpp#L1205) and the check @Sandern is referencing then indeed prevents those off-mesh connections between layers from being removed ([here](https://github.com/recastnavigation/recastnavigation/blob/6285b17587bf06d2d71a32df74e22e1d18da93fc/Detour/Source/DetourNavMesh.cpp#L366), for posterity).

**Comment by memononen** [comment]
Looks like tile internal off-mesh links also get `side = 0xff`. I think that explains skipping those links. So I'd say it is safe to remove `tile->links[j].side != 0xff`.

**Comment by Janiels** [comment]
I may have misunderstood this. I read it as if the problem was that off mesh connections between layers in the same tile location were not being disconnected. Reading the code, it looks like any external link between layers in the same tile location are connected with `side = 0xff`, so indeed these are not disconnected.

@Sandern Did I misunderstand? Can you clarify what you mean by tiles in the same layer?

**Comment by Sandern** [comment]
@Janiels You are right, description was not correct. It's between layers in the same tile location.

**Comment by Janiels** [comment]
PR is at #139 for it. Thanks for the report!
