### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by hymerman** [recastnavigation/recastnavigation#126]
We should absolutely get some kind of CI set up! Let's talk about how we should go about doing this. This conversation is split out from #123, here's what's previously been said:

@hymerman
>Next I'd love to get Continuous Integration set up - I've actually already got a pull request open for this :) (#89). I see you've got a really nice AppVeyor setup in your fork, @rwindegger - let's get that merged in if it's easy to separate from the other things merged into your fork, and we'll use my Travis setup. I updated to premake5, and I see you've updated the way lots of dependencies work with submodules, which is also cool.

@rwindegger
>The CI should be easy to port over, I've uploaded VS Solutions to the repo, I should have adjusted the premake file.
>
>Most of the Submodule stuff I did is for the dependencies of the Demo. The rendering of the UI was completly adjusted to use https://github.com/ocornut/imgui. I've updated to SDL2 instead of SDL. And did a gh-pages push for the doxygen documentation. FastLZ is pulled in from https://github.com/ariya/FastLZ and stb is pulled in from https://github.com/nothings/stb.
>
>All in all the Demo changes will be a fast port too. Just need to do it a little more structured than i did it in the first place.

**Comment by grahamboree** [comment]
With Travis you can run pre-build scripts to do things like install dependencies.  I'm not as familiar with appveyor, but I'd imagine it's similar.  Is this something we can do on there as well?  If so, we can use it to run premake to generate the sln, rather than keeping it in the repo.  We'd also need to set it up to download SDL and unpackage it in the right place.

I'm reluctant to start checking in dependencies and sln files, just because as a platform-independent project, things can get out of sync.  I imagine most people are using Windows, so if new dependencies or build settings are tweaked in the sln, there's a chance they wouldn't get carried over to linux or OSX.

**Comment by hymerman** [comment]
Already done in my pull request :) yep, appveyor can do the same. You're
right, we definitely shouldn't have project files checked in.

**Comment by hymerman** [comment]
For reference, my PR is #89

**Comment by hymerman** [comment]
@rwindegger, I'm going to update my PR to remove the prebuilt premake and get that committed both for Travis and AppVeyor, since any CI is better than nothing! When you've separated out what you need to separate out, just replace my AppVeyor config with your own.

**Comment by hymerman** [comment]
@rwindegger - oh sorry, I misunderstood what you said about VS solutions - you'll need to do a little merging actually, shouldn't be hard though!

**Comment by hymerman** [comment]
Merged in with #131
