### ISSUE TITLE
replace premake with cmake

### ISSUE THREAD

**Issue by wbierman** [recastnavigation/recastnavigation#171]
I would like to request that cmake be considered as an alternative to premake.

**Comment by Janiels** [comment]
Unless I am mistaken the premake5 we use is the latest version. I personally have had much worse experience with CMake than I have with premake, albeit I only use the latter for this repo. Is there any specific issues you are having with premake?

**Comment by wbierman** [comment]
Is it really?  I feel like I had to go find premake4 in order to make it work.  But no, no specific issue.  I just think cmake is much, much more pervasive.

**Comment by grahamboree** [comment]
Historically, the project used Cmake at one point, but was switched to premake (in be4d6fc180af8da075823089c0244df81f676e42) before I was heavily involved, so I can't speak to the rationale there.  Here's a thread on the mailing list where it was discussed.  https://groups.google.com/d/topic/recastnavigation/-RwtFL1j4gE/discussion

We just, however, updated to the latest version of premake5.

We've talked about switching back to cmake, but we couldn't really come up with a terribly compelling reason to, other than that it's more popular in the C++ community.  Apart from that, premake seems to have some benefits over cmake, most notably that the configuration is in lua, rather than the cmake DSL, which game developers are often more familiar with.  I'm happy to hear out arguments for switching to cmake, though.

**Comment by grahamboree** [comment]
The instructions in the readme tell you to grab premake5 and the file is named "premake5.lua" :wink:

**Comment by wbierman** [comment]
Okay, yes sorry I was wrong about that.  I have updated my original post.

**Comment by wbierman** [comment]
> Here's a thread on the mailing list where it was discussed. https://groups.google.com/d/topic/recastnavigation/-RwtFL1j4gE/discussion

If I understand what I've read there correctly, one of the advantages/intents of using premake is that it takes the build-file generation out of the hands of the users and places it in the hands of the maintainer(s).  To me, this implies including common build environment build files in the repository, generated by you, using premake.  This is not currently done.

**Comment by Janiels** [comment]
We are mostly worried about building the demo. The way we suggest integrating R&D is just by copying the few folders of source/include files you need across. I think integrating the demo does not make very much sense - it is meant to give an example of how to use R&D.

**Comment by grahamboree** [comment]
> To me, this implies including common build environment build files in the repository, generated by you, using premake. This is not currently done.

This is moot.  We're using it in the same way you'd use cmake.

**Comment by wbierman** [comment]
> The way we suggest integrating R&D is just by copying the few folders of source/include files you need across.

Um, why?  The way I have always used it is I will place the full, unmodified repository into a subdirectory within my repository, and configure my build to include the relevant files from that subdirectory.  And now that this project is on git, more specifically I use a git submodule for it.  It makes updating which revision I use trivial (absent any breaking changes).

> This is moot. We're using it in the same way you'd use cmake.

That was my point.  The stated benefit of switching to premake has not been realized.

My only other real thought on the matter is that, in general, I would want a strongly compelling reason to require my users to install a relatively obscure third-party application such as premake.

**Comment by Janiels** [comment]
> Um, why? The way I have always used it is I will place the full, unmodified repository into a subdirectory within my repository, and configure my build to include the relevant files from that subdirectory. And now that this project is on git, more specifically I use a git submodule for it. It makes updating which revision I use trivial (absent any breaking changes).

Why not? That is not to say that I wrote that part of the readme (I think Mikko did way back when), but it makes perfect sense to me. C++ is not exactly known for its ease of 3rd party dependencies. Copying the source files you need is a very easy way of integration, and the files are portable and well structured. Plus you only get what you need, compared to getting random test meshes, fonts, readme's and screenshots, that exist in the demo.

I don't feel CMake would make integration particularly easier; I think the source copy is as easy as it gets. And you are saying that you integrate R&D by configuring your build to pull in the relevant folders; this already sounds easier than merging one CMake config with another.

**Comment by grahamboree** [comment]
FWIW git submodules are just a fancy way of copying source files into your project directory.

I don't think any of us are outright against switching to cmake.  There just has to be a clear, objective reason to make the switch.  IMHO popularity alone is not intrinsically beneficial.  It does, however, very often bring with it objective benefits, like integration with third party tools and pipelines.

@wbierman We're not going to switch for the sake of switching.  I think this discussion will move forward more productively if we can talk about what benefits we get from cmake, rather than what's not to like about premake.

**Comment by wbierman** [comment]
I know what git submodules are for.  Thanks though. :+1: 

We are actually have two separate conversations in this thread.  One was intentional and one was not.

> Copying the source files you need is a very easy way of integration

It is both tedious and dangerous to have to select which files to copy from this repository any time you want to update to a more recent revision.  It is safer and faster to just do a submodule update.  Let us agree to disagree on this topic as it is not relevant to the issue.

I am fine continuing to use cmake to build Recast.  Adopting cmake for RecastDemo or not does not affect my ability to use Recast.  I only opened this issue to raise the question of whether anything is gained by forcing those who want to compile the demo to install this obscure third party build system.

@grahamboree the benefit is ease of use by users of this library, as I imagine many will already have cmake installed.

**Comment by hymerman** [comment]
A few relevant points:

* Premake isn't obscure, I've used it in a couple of workplaces before and many colleagues know about it. CMake is clearly more popular but I think calling premake 'obscure' is unfair.
* I haven't had to 'install' premake - I've just downloaded the executable and ran it, both on Windows and Linux. It doesn't feel like much of a burden.
* (as mentioned already) It's only for the demo; if you're just using the library you just use the source directly and don't care how the demo gets built.

If any of those points wasn't true (so if premake was genuinely confusing for users, hard to use, or required to integrate into other codebases) I think there would be a good reason to make the effort to switch, but it's not, so I'd rather leave it alone.

That said, if someone *did* make the effort and open a PR for CMake support, with everything working as well as it does now, with Travis and AppVeyor support, I'd accept it purely because CMake is more popular - I just don't personally think it's worth anyone's effort!

**Comment by memononen** [comment]
The historical reason not to use CMake was that it did not fit at all to my workflow. I wanted to have a Xcode project with a bunch of extra warnings, and I preferred "native" project files per dev env. Could not figure out how to do that in CMake. And I absolutely hated the litter of cmakefiles on each subdir. I have particularly short fuse what it comes to tinkering with make files (on a good day it maxes out around 15 mins :)). So the dominating factor became something that I can maintain personally.

**Comment by hdnshare** [comment]
It's been more than one year, I think CMake has improved a lot. Please check [Ogre 2.1](https://github.com/OGRECave/ogre/tree/v2-1) [CMake script](https://github.com/OGRECave/ogre/blob/d0fa5d0209340519e952eb1bbeccf714609b90ed/Samples/2.0/Tutorials/EmptyProject/CMakeLists.txt), I learn a lot from it. And CMake has a GUI :) Of course premake is fair (no need to install, but CMake GUI no need to install too). But with CMake, you can do a lot of options (choose build path so that the build file won't blend with the source file,... ). Anyway, there is 2 good points to reconsider:

- CMake is popular (also has GUI, it's a plus)
- If you have problem with CMake, you can see how other projects deal with this problem.

**Comment by hymerman** [comment]
Those are some good benefits, but premake is working well, and there's a fair amount of effort required to switch (holy moly, the Ogre CMake scripts are thousands of lines long across many files!).

If someone were to submit a PR replacing premake with an equivalently-functional set of CMake files, all working with Travis, I'd be happy to accept that.

I think that's all stuff I said last year actually :) Nothing has really changed except that CMake is a bit better.

**Comment by hdnshare** [comment]
I don't have much to offer, but I have a simple CMake script
[recastnavigation.zip](https://github.com/recastnavigation/recastnavigation/files/1477153/recastnavigation.zip)
 that help to create the projects for Recast Detour library (I know it is recommend to add the cpp & h file into the integrated project, but I prefer linking the lib for easy update management).
Note: I create this script base on Ogre 2.1 CMake script. So this could be a  good start to make CMake an official Cross Project Maker along with premake5.
