### ISSUE TITLE
Create CONTRIBUTING doc

### ISSUE THREAD

**Issue by hymerman** [recastnavigation/recastnavigation#174]
Mikko suggested (here: https://github.com/recastnavigation/recastnavigation/issues/123#issuecomment-162223614) that we should have a CONTRIBUTING.md doc along with a code of conduct.

For the code of conduct, Mikko's suggestion of the todo group template looks good to me:

http://todogroup.org/opencodeofconduct/

I suggest we use this, and add it as either "CODE_OF_CONDUCT.md" (goes well with the all caps README and CONTRIBUTING docs) or "Conduct.md" (my preference) in the root. These seem to be the two usual names for it in other open source projects.

For the CONTRIBUTING doc, Mikko suggested something like this one by facebook:

https://github.com/facebook/react/blob/master/CONTRIBUTING.md

However, of all the docs I've seen, I actually like the angular.js one the best:

https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md

I propose we take this, and remove or adapt the irrelevant bits to suit our project.

**Comment by Janiels** [comment]
Personally I don't think codes of conduct add much value - they should really go without saying. To me it seems like it's just something that everyone adds to their open source projects to be politically correct. "Be respectful" - oh, okay, I will now that there is a document that says I should. :smile:
To be clear I have no problems with adding one, I just don't see the value in them, so I can't really comment on that particular one.

For the contribution document:
The Angular one is a little long, but I suppose that would be reduced since R&D is a bit smaller of a project. For commit message format I think we should use something like the .NET foundation, which can be seen [here](https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/contributing.md#commit-messages); it also looks quite a bit simpler than Angular's.

**Comment by grahamboree** [comment]
I agree. I don't think we necessarily need *everything* the angular doc has, but a lot of it is relevant.  It also provides a nice framework for us to model future additions and modifications after.  Having conventions like "squash commits before submitting PR's" and the like in a centralized location is great to refer people to, rather than just addressing these things on a case-by-case basis.

A code of conduct is something I think is best to have and not need.  It's easier to refer someone to a document that they implicitly agreed to than address their behavior individually.  There's not a lot of downsides to having one, and if it never gets used, (which it probably won't) all the better.  :smile:

**Comment by Janiels** [comment]
Sounds good to me. :1:

**Comment by memononen** [comment]
@Janiels rules written on the wall save a lot of trouble when things go south. Something as simple as "hey you, don't do that, it is against our rules, see here" is way more effective (no speculation needed) and easier (all community members can do that) than trying to explain why some behavior is bad. Gladly, I have had only a handful of incidents over the years (mostly bad behavior towards me). It's a good thing to have and a positive signal to a potential contributor that things are handled nicely here.

**Comment by Janiels** [comment]
@memononen I see. It's probably just because I'm inexperienced being on this side of the fence. :)

**Comment by jackpoz** [comment]
Code of Conduct seems to be a trending topic across OSS world, I find http://www.infoworld.com/article/3026196/open-source-tools/are-codes-of-conduct-dangerous-to-open-source-software-development.html and the linked https://github.com/domgetter/NCoC very interesting
>What is NCoC
No Code Of Conduct is a groundbreaking new idea. Designed to help you find communities and projects that will not get stuck endlessly debating how members should behave in their communities, only to be found to never be fully resolved to anyone's liking.

>This project adheres to No Code of Conduct. We are all adults. We accept anyone's contributions. Nothing else matters.

**Comment by hymerman** [comment]
Hmm. Not totally sure I agree with the linked viewpoints. The NCoC literally says "Whatever you do, don't make a scene", which is a somewhat outdated approach to discrimination to say the least. And the chap in the infoworld article seems to be claiming that codes of conduct are another form of repression which is rather facetious. If he's genuinely fearful of losing his job over CoC violations he's probably done something really quite bad.

To be clear, we're going to be sensible in managing this project (no 'endless debates'), and will adopt a CoC document that we can point to should anything happen that would be a "grey area" without the doc. We won't be aggressively ramming it down anyone's throats. As in the good bit of the NCoC, "we're all adults". That's all.

My point of view is that I don't 100% understand the value of such a document, but that as a white middle class male I probably wouldn't. If it helps someone else and all I have to do is add the doc, and continue trying to be a nice tolerant guy, then that's a good tradeoff.

**Comment by memononen** [comment]
I had pretty much what @hymerman said in my mind when I suggested having the CoC. IMHO, it is the right side to err in case of no strong opinions :)

**Comment by grahamboree** [comment]
NCoC seems a bit...brash.  Lets just use the auto-generated one that @hymerman linked and save the brain cells for other things :stuck_out_tongue:
