### ISSUE TITLE
Can increase the ray function?

### ISSUE THREAD

**Issue by malong007** [recastnavigation/recastnavigation#189]
Ray can be calculated at any position, from the start point to the end point of the collision between
Based on the navmesh

**Comment by malong007** [comment]
Allow the air projection rays

**Comment by hymerman** [comment]
I'm not totally sure what you're asking - are you asking for support for raycasting against navmesh geometry as if the navmesh was collision geometry? As in, you would like to find the intersection between an arbitrary 3D ray and the navmesh geometry?

If that's what you're asking - I don't think something we are going to support (unless someone gives a very good example for its use), since it's outside the scope of the library. The navmesh geometry is in a format designed to support navigation queries, and spatial queries in navmesh-space only. If you want general spatial queries, you'd be better off extracting the navmesh geometry into some spatial data structure and using another raycasting library. I've done this before with RaycastMesh, a nice simple project by John Ratcliff: https://code.google.com/archive/p/raycastmesh/

If that's not what you're asking, can you try again to explain what you need?

Thanks!

**Comment by hymerman** [comment]
I'll close this for now as I have a feeling it's a feature request that we're not going to implement. @malong007 if you have any more input, please leave it here as a comment and we can reopen the issue.
