### ISSUE TITLE
How to find a landing point from the sky?

### ISSUE THREAD

**Issue by malong007** [recastnavigation/recastnavigation#197]
How to find a landing point from the sky?
For example, when the game editor, a monster was accidentally placed in the air, how to use the code to enforce the ground?

**Comment by hymerman** [comment]
Try using `dtNavMeshQuery::findNearestPoly` - it's easy but can find polys above the character if they're that high up - maybe that's acceptable for you. If not, use `dtNavMeshQuery::queryPolygons` with `extents` and `center` set to a tall box below the character, then iterate the returned polys to decide which one is closest to the character.

In both cases you'll want to use `dtNavMeshQuery::closestPointOnPoly` to get a precise point on the returned poly.

Does that help?

**Comment by malong007** [comment]
Thank you for your reply.
If I just want to get to the ground in a vertical position, can I do it?

**Comment by Janiels** [comment]
You can use `dtNavMeshQuery::queryPolygons` combined with `dtNavMeshQuery::getPolyHeight` to constrain it in the XZ direction.

**Comment by malong007** [comment]
Is there a more convenient API?

**Comment by hymerman** [comment]
No, we would have said if there was ;) Janiels' suggestion should result in a very small chunk of code though - just put that in a function and reuse it if it's something you do frequently.

Since different games will have different ways of doing this (e.g. games featuring open terrain vs. games with stacked floors in a building), if there _was _ a method in the API to do it, it would have enough variants that they might as well not be there - just combine existing methods to get what you want.

**Comment by hymerman** [comment]
Closing this as I think we've given as best an answer as we can :)
