### ISSUE TITLE
Is there a RVO implementation?

### ISSUE THREAD

**Issue by malong007** [recastnavigation/recastnavigation#201]
Is there a RVO implementation?
DetourCrowd better than RVO?

**Comment by hymerman** [comment]
No, the avoidance algorithm in DetourCrowd isn't RVO, and RVO isn't provided as part of the project at all. Unfortunately licensing is rather awkward - RVO is owned by the University of North Carolina and whilst we could integrate it (since we're an open source project), their license terms would mean anyone who uses Recast/Detour in a commercial project would have to contact UNC and pay to use it. I've heard this can be around $50,000.

http://gamma.cs.unc.edu/RVO2/

**Comment by malong007** [comment]
thanks, got it!

**Comment by hymerman** [comment]
No problem :)
