### ISSUE TITLE
How to check a position is valid?

### ISSUE THREAD

**Issue by 1050676515** [recastnavigation/recastnavigation#233]
How to check a position that can arrived or not

**Comment by Janiels** [comment]
Use `dtNavMeshQuery::findNearestPoly`, like [here](https://github.com/recastnavigation/recastnavigation/blob/d9c6fc58ce1169c74a9d24713f7b5929b93aa526/RecastDemo/Source/NavMeshTesterTool.cpp#L686).
You can use it to find the nearest polygon and point on that polygon so you can check your distance to the mesh.

**Comment by 1050676515** [comment]
What does check distance to the mesh mean?
`
	dtPolyRef ref;
	m_navQuery->findNearestPoly(pos, extents, &m_filter, &ref, nullptr);

	if (!ref || !m_navMesh->isValidPolyRef(ref))
	{
		return false;
	}

	const dtMeshTile* tile = nullptr;
	const dtPoly* poly = nullptr;
	if (dtStatusFailed(m_navMesh->getTileAndPolyByRef(ref, &tile, &poly)))
		return false;
`
I got the dtMeshTile and dtPoly, but I don't know how to check it

**Comment by Janiels** [comment]
`findNearestPoly` returns the closest polygon (ref) in your example, and the closest point (but you are passing `nullptr` for this parameter).
`findNearestPoly` does not necessarily guarantee there is mesh within the `extents` passed - so you can further check the distance to mesh by checking the distance to the closest point (so make it return the last argument and check distance).

**Comment by 1050676515** [comment]
But there are two kinds of situations.
the position (I wanna know it can arrived or not) may be in the polygon (return by findNearestPoly) or may be not in the polygon.
So should I check whether the position in the poly or not first, and then call findDistanceToWall to check the distance?

**Comment by Janiels** [comment]
If you want to know whether it is inside the polygon in 2D you can use `dtNavMeshQuery::getPolyHeight` after `findNearestPoly`. It returns `DT_FAILURE` if the point is not 2D-contained in the polygon. You can also specify some very small X and Z extents in the `findNearestPoly` call.

**Comment by hymerman** [comment]
Closing since this seems resolved now.

**Comment by admbbs** [comment]
> If you want to know whether it is inside the polygon in 2D you can use `dtNavMeshQuery::getPolyHeight` after `findNearestPoly`. It returns `DT_FAILURE` if the point is not 2D-contained in the polygon. You can also specify some very small X and Z extents in the `findNearestPoly` call. Another alternative is `dtNavMeshQuery::closestPointOnPolyBoundary`. If point is 2D contained in the polygon, `closest` will be exactly equal to the point.

It seems that `dtNavMeshQuery::getPolyHeight` is not a good choise. When I tried to determine if a position is reachable, and that position happened to be on the edge of one of the poly's, `dtNavMeshQuery::getPolyHeight` returned `DT_FAILURE` because `dtPointInPolygon` returns false in cases like that. So I finally chose the *check-the-distance* approach and implemented something like `dtVequal2D`.

Is this the case, or am I missing something? Thanks!

**Comment by memononen** [comment]
`getPolyHeight()` should be sloppy enough to return height after call to `closestPointOnPolyBoundary()`.
 
@jakobbotsch looks like you introduced it there 2yrs ago, looks like innocent optimization, but it's not correct.

In practice we dont know if points are inside the polygon, `dtPointInPolygon()` should be used in case where we can optimize certain calculations for points which quite likely inside the polygon (i.e. has about constant value, and calculating edge cases is complex), but it should be never used to actually check if point is inside a polygon.

**Comment by jakobbotsch** [comment]
The change in #381 was not an optimization, it was to fix #343 and the problem that was exposed in #373.

> getPolyHeight() should be sloppy enough to return height after call to closestPointOnPolyBoundary().
> 
> @jakobbotsch looks like you introduced it there 2yrs ago, looks like innocent optimization, but it's not correct.
> 
> In practice we dont know if points are inside the polygon, dtPointInPolygon() should be used in case where we can optimize certain calculations for points which quite likely inside the polygon (i.e. has about constant value, and calculating edge cases is complex), but it should be never used to actually check if point is inside a polygon.

I'm not sure I agree. If the user wants to check whether a point is inside a polygon, then using `getPolyHeight` will tell you that. Due to floating point inaccuracies we can never be 100% correct, so we have to be either overly conservative or overly liberal.
It might seem confusing that `closestPointOnPolyBoundary + getPolyHeight` can fail, but really this combo should just be replaced with `closestPointOnPoly` which is completely robust.

**Comment by jakobbotsch** [comment]
I suppose what exposed the behavior was when `dtClosestHeightPointTriangle` was changed to have no epsilon. Maybe we can change that back, but I'm not sure if we then fail to handle degeneracy again.

**Comment by memononen** [comment]
Due to floating point accuracy (and how things are implemented) we cannot say for sure if a point is inside a polygon. I.e. if you find nearest poly and constrain point to it, point in poly can say no. We can find nearest poly, but we cannot say for sure if a point is inside it. Point in poly can be used for things like calculating SDF of a polygon (if you can accept that the result is wee bit wrong around the boundary). 

`getPolyHeight()` should work so that the points returned by the API always return valid height too. That includes things like results from raycast or moveAlong. It should be thing to add height to a 2D result. So it should be super sloppy. Maybe it should have been called `samplePolyHeight()` and indicate that it extrapolates.

Maybe `getPolyHeight()` should be just call to `closestPointOnPoly()` returning the height.

My minds default is still that `closestPointOnPoly()` does the euclidean distance check and `getHeight()` is the down-cast version, which is not the case anymore :)

I used word "should" but ultimately it's your call.

**Comment by admbbs** [comment]
Thanks for your replies! They really help.
