### ISSUE TITLE
Pathing from underground to ground Error

### ISSUE THREAD

**Issue by ryancheung** [recastnavigation/recastnavigation#262]
Agent under ground should not be able to generate a path through ground surface, or vice verse.
This cause bugs that creature can go through walls or go through buildings in pathing.   

![image](https://cloud.githubusercontent.com/assets/240899/22860575/fa2b30fc-f13c-11e6-815b-2aa30bbc189d.png)

**Comment by hymerman** [comment]
We'll need a bit more information to see if this is actually a bug - have you hooked up the debug draw callbacks? If so can you post some screenshots of what broken paths you're getting?

Usually what happens when you get paths going through the ground, is either:
 * The navmesh doesn't line up perfectly with the visual mesh - it won't since it's just a simplification, and your game code should perform some kind of raycast to place characters on the visual ground.
 * You have underground and overground areas very close and are generating the navmesh with an unreasonably low walkable height, which means that when paths are requested, it's possible that the start point which should be underground, is actually closer to the navmesh on the next level up. You should look at the nav geometry and draw the actual start/end points to see if this is happening.

**Comment by ryancheung** [comment]
@hymerman I guess the problem is related to the walkable height, since if I increase the walkable heigh, the problem is gone. Currently the config.walkableHeight is 6, set it to 10 then the problem would be gone.

**Comment by jackpoz** [comment]
that screenshot looks like the result of a debug ingame command of a known project, with totally custom pathfinding code that slightly relies on recast&detour (and I do recognize the project there :) )

**Comment by hymerman** [comment]
Since there's no more input from @ryancheung , and it doesn't look like an issue with Recast, I'm going to close this.
