### ISSUE TITLE
Height error in Sample_TempObstacles？

### ISSUE THREAD

**Issue by liuyanlin** [recastnavigation/recastnavigation#267]
Sample：Temp Obstacles
Input Mesh：nav_test.obj

i  try and tune the every param in exe. but 'render height' not cover higher ground
when “ Sample = Tile Mesh” ，dont change param , that normal render ，seems fines.

is my params question?
What can I do to normal render？

**Comment by jakobbotsch** [comment]
I'm not sure I quite understand the question, but I assume it is to do with polys not matching up with the terrain when using the temp obstacles sample.

The detailed mesh is what provides height detail and allows the tiled and solo meshes to match polygons snugly to the terrain. However temp obstacles work by rebuilding tiles whenever changes are made, and for that to work efficiently the tiles are small anyway. For small tiles there usually is no need to have height detail, which is why the detailed mesh is not built for the temp obstacles.

Our recommendation in these cases is usually to lower your tile size or switch to a tiled mesh.
Do note that the polygons are there, they are just cutting "below" the terrain because of simplification.

**Comment by hymerman** [comment]
Closing this since there's no more input from @liuyanlin and a good answer was given - if you are still having problems, reply and we'll reopen the issue.
