### ISSUE TITLE
rcSpan bitpacking counterproductive?

### ISSUE THREAD

**Issue by mbabinski-at-google** [recastnavigation/recastnavigation#286]
I noticed that bumping up RC_SPAN_HEIGHT_BITS to 16 _dramatically_ reduces processing time for my batch map processing job. It finishes in 500 minutes instead of 850, presumably because the bitops required for accessing 13-bit fields aren't trivial. With clang on x64, sizeof(rcSpan) is 16bytes regardless. Is saving 4bytes/struct on i386 worth the processing cost?

**Comment by jakobbotsch** [comment]
I would be fine with a patch that increases the size. It would allow us to support larger worlds out of the box too -- I have had to increment this value because of tiles with large differences in the Y coordinate in my own worlds.

That said it is unexpected to me that the difference is so dramatic. We do several floating point computation for each of those accesses, and it should be just a single shift and mask operation. But `addSpan` could be made more efficient too (to avoid recomputing the value in a few places).

**Comment by mbabinski-at-google** [comment]
Hm. I'll re-run my jobs to get some more numbers.

**Comment by mbabinski-at-google** [comment]
Well, I can't reproduce my miracle results, so chalk that up to operator error.
