### ISSUE TITLE
connectExtLinks does not connect to neighbourtile which has only one polygon

### ISSUE THREAD

**Issue by MINIONBOTS** [recastnavigation/recastnavigation#296]
![untitled](https://user-images.githubusercontent.com/2842405/34434995-a07dd290-ec8a-11e7-88bc-0f7b897979bf.png)

On the left side there are 3 tiles in total, separated by a thin white line. The blue polygon belongs to it's own tile and it is the result of a findpath. The single polygon there has no link to the neighbourtile. 
Now on the right pic, I slightly expanded that not working part and the tile now holds two polygons and this is where recast sets a link to the neighbour. 

I starred at dtNavMesh::connectExtLinks now for quite a while, but I would guess there is a bug in the recast / mesh building itself. Can someone maybe give me a tiny hint where I could look ?

**Comment by MINIONBOTS** [comment]
The issue disappears when I comment out the 
'
// Skip edges which do not point to the right side.
if (poly->neis[j] != m) continue;
'
inside findConnectingPolys(..)

**Comment by MINIONBOTS** [comment]
It happens also inside a tile, when the formed polygone is rather small and on an "outer corner". I guess I can work around this by adjusting the detail samlpe values, but it is kinda annoying.

**Comment by jakobbotsch** [comment]
This usually happens because of using some wrong bounding box as opposed to the cell size + resolution. Make sure your bounds are exact multiple of cell size and resolution (best is to specify your tile size in cells, and compute the actual in-game bounds using `cs * resolution`.

In any case if you could build a .gset and .obj for your terrain that reproduces the issue in the demo it would help a lot. You can check the format in `InputGeom::saveGeomSet`.

**Comment by MINIONBOTS** [comment]
Turned out it was actually my bad...that's why I shamefully closed the issue ;) 
I managed to merge the recast mesh with my own octree based 3d-cube-mesh, and over all of that I build another auto-generated-macromesh to fix the bottleneck for huge meshes or super complicated/long paths. While finding the path through the recast polygones, I kinda did a ' if i != 0 ' instead of 'if i != DT_NULL_LINK' ..shame on me. But thanks for your answer!
