### ISSUE TITLE
Get Strange path for "path follow" and "path straight"

### ISSUE THREAD

**Issue by Weilin1992** [recastnavigation/recastnavigation#302]
![strangepath](https://user-images.githubusercontent.com/14081305/34649270-a5030f84-f3e6-11e7-8663-4b7d00c35bfa.png)

- As illustrated above,  the path from start position to the end position should be a straight line, but actually the line first reach the cross point of several polygens' edges and then to the end position.

**Comment by jakobbotsch** [comment]
Unfortunately this is to be expected due to the way the A* search (`findPath`) needs to reduce polygons to a point to work. You can see the points being used by using the "Navmesh Nodes" mode in the demo. It should show what is happening here.

There are many ways to improve the result, for example a simple way is to raycast ahead a few points and see if there is a direct path, and if there is, go directly to it. You can also use `dtPathCorridor`; see `dtPathCorridor::optimizePathVisibility`.

**Comment by admbbs** [comment]
> Unfortunately this is to be expected due to the way the A* search (`findPath`) needs to reduce polygons to a point to work. You can see the points being used by using the "Navmesh Nodes" mode in the demo. It should show what is happening here.
> 
> There are many ways to improve the result, for example a simple way is to raycast ahead a few points and see if there is a direct path, and if there is, go directly to it. You can also use `dtPathCorridor`; see `dtPathCorridor::optimizePathVisibility`.
> 
> The problem happens more when long thin polygons are next to larger "rounder" polygons. This often happens when using monotone partitioning, which is used by the tile cache always. One thing that can alleviate this issue somewhat is by reducing tile size, since that puts a bound on the size of polygons created.

In your previous reply you said "There are many ways to improve the result". Could you please give me any hint about any other ideas? That "raycast" approach is the only way I came up with. T_T

Maybe I could let `findPath` (the A* algorithm) output more than one result, and run the `findStraightPath` ("string pulling") on each of them to pick the best one? However it seems that the time cost could be unacceptable.

Thanks!
