### ISSUE TITLE
STL in Recast & Detour

### ISSUE THREAD

**Issue by jakobbotsch** [recastnavigation/recastnavigation#315]
The decision not to use STL and be very strict with dynamic memory allocations in Recast & Detour is starting to show up in a lot of places where it hurts us. For example:
#307: Can be solved easier with a simple queue
#314: Shoehorning data-structures into the existing `rcIntArray` as separate fields (actually we do this in a lot of places)
#151: Turns out `rcIntArray` was not optimized well
I am sure there are more. I suggest that we get rid of our own dynamic data structures and begin using STL instead. I think the old reasons not to use STL are largely obsolete by now: STL should be well optimized on almost any relevant platform. and the dynamic allocations we need are usually so small that the memory allocated should not be a problem.

Thoughts?

cc @grahamboree, @hymerman, @memononen

**Comment by jakobbotsch** [comment]
I want to make it clear that I don't suggest drastic changes; for example, span allocation code and such should be left as-is (it has been carefully thought about to be as good as possible). It is mainly in places where there are glaringly obvious solutions to problems that we have needed to avoid for STL reasons.

**Comment by hymerman** [comment]
My personal opinion is that yes, we should allow use of the STL in both Recast and Detour. That definitely doesn't mean we shouldn't be careful with memory allocation of course :) But I agree completely that there are cases where STL containers etc. will make code clearer, less robust and potentially even faster. I've never liked `rcIntArray`!!

This is something that should go towards a 2.0.0 version I guess, since it's a change in the library's dependencies.

**Comment by memononen** [comment]
I've had a lot of feedback over the years thanking that Recast did not use STL.

Most game studios where I have worked have not used STL, for one reason or other. The two most common reasons have been that: 1) different implementations on different platforms have small subtle differences, which makes hard to find bugs, 2) dealing with custom allocators in STL is pain, not impossible, but just super annoying.

In some cases it makes sense to roll your own algorithm to better match your data structure/access pattern, but that is problem with all general purpose code.

I definitely went too far with repurposing the int array. A lot of tool code I worked with at that time were really sloppy with allocations and data structures, and thus slow. There were maps of vectors of sets of strings. I wanted restrict myself on dynamic allocations.

I think you should choose the way that you feel comfortable maintaining. I lightly recommend to not use STL at runtime (Detour), and if you use it in Recast, make sure it works with the custom allocators.

**Comment by mbabinski-at-google** [comment]
FWIW, I've been working up a PR that wraps rcAlloc/rcFree in an STL-style allocator, and turns rcIntArray into a wrapper around std::vector. I understand some trepidation around using std::map, etc., on account of the complex RB-tree implementation and somewhat surprising performance profile, but vector is well-understood, straight-forward, and arguably the correct structure to use 80% of the time. IMO, a reasonable approach is to make rcFoo versions of a few white-listed structures (like vector), and use them as appropriate.

**Comment by jakobbotsch** [comment]
> This is something that should go towards a 2.0.0 version I guess, since it's a change in the library's dependencies.

I'm not sure if this is considered a new dependency when it's part of the C++ standard library?

> I've had a lot of feedback over the years thanking that Recast did not use STL.

Good to know, I wasn't aware of any feedback.

> In some cases it makes sense to roll your own algorithm to better match your data structure/access pattern, but that is problem with all general purpose code.

Right, but I think it is a problem when we let this significantly complicate the code, for example leading to the bug described in #307. However, now that I think about it we probably wouldn't even want to use STL here -- it would lead to a dynamic allocation on every call to `update`.
Actually, the main thing we need in many cases is a good `std::vector` substitute, like @mbabinski-at-google has realized. LLVM's [`SmallVector<T>`](http://llvm.org/doxygen/classllvm_1_1SmallVector.html) might be exactly what we should strive for -- it can be used to avoid dynamic allocation in common cases, but fall back on dynamic allocation when more elements are needed.

I must admit that I dislike having to copy our implementations between both Recast and Detour, and also that we do not get the performance optimizations that many clever people have done to STL data structures. But perhaps this is an ok trade-off.

**Comment by mbabinski-at-google** [comment]
I submitted #316. IMO, it makes the code more readable, and as of yet, doesn't change external interfaces. It would likely be easy to move all of the STL-specific code into private headers, if that's a concern.

If the STL version is rejected, I think homebrewing an rcVector<T> is a superior option to manipulating arrays of ints, though it is still a shame to duplicate the efforts of the various STL authors.

SmallVector is very nice, but, from what I've seen in the corner I've been mucking in, most of Recast's vectors are anything but small =)

**Comment by SpangMcgraw** [comment]
Our studio just doesn't use STL, when I mentioned this to my head he was
very adamant that we would not take changes that introduced the user of it,
and pretty much echo'd the points made by Mikko.

Homebrewing a data structure would be far more preferable for cross
platform consistencys sake.

**Comment by memononen** [comment]
@jakobbotsch Fixed buffer sizes are always tricky. Either you have to prove that the fixed size buffer is good for all cases, or document precisely what happens when you drop stuff on the floor. There are two patterns I have used for growing since: 1) buffered callbacks, 2) allocate pages to grow the buffer.

Bufferred callbacks are good in a case where you call an API and are interested in one result (i.e. find nearest polygon). The idea is that instead of returning an array, you pass in a callback, but it gets called with N items (i.e. 32 polygons) instead of one. This generally hides the function call overhead.

Pages allocations means that you grow the list by a big chunk at a time. Avoids copying on grow and you can often trade off cache usage too since you are likely to touch a chunk of linear memory at a time. Good for cases where you generally do linear iteration over the array, a bit nasty for random access.   

I think the right solution to #307 would be to dynamically grow the buffer, not complicate the code. I faintly remember that idea for dynamic obstacle update was that if the buffer was full, adding/moving the obstacle would fail, and the caller should retry until success. Might not be the best strategy.

Also sounds like many of the problem cases currently are related to growing an array, so something like rcVector (even SmallVector style) could be an excellent idea.

**Comment by jakobbotsch** [comment]
I think based on the feedback (both from @SpangMcgraw and from @memononen) that we should not allow STL then. In reality we probably only need a good dynamic array, as discussed, so limiting it to that should be ok.

**Comment by mbabinski-at-google** [comment]
FYI, I made a PR (#318) to add an rcVector that mostly copies the STL vector api.
