### ISSUE TITLE
About getPortalPoints is called in findRandomPointAroundCircle 

### ISSUE THREAD

**Issue by fananchong** [recastnavigation/recastnavigation#330]
at line: 417

```c++
// Find edge and calc distance to the edge.
float va[3], vb[3];
if (!getPortalPoints(bestRef, bestPoly, bestTile, neighbourRef, neighbourPoly, neighbourTile, va, vb))
    continue;
```

this condition is always false. (use dtStatusFailed is better?)

**Comment by jakobbotsch** [comment]
Good catch. This mistake is also there on lines 2818, 2989, 3176. `dtStatusFailed` is the correct fix -- do you want to submit a PR for it?

By the way, it does not cause problems on any of these lines because the function cannot fail here (it only fails if a link cannot be located, but the link has already been located in the parent function).

**Comment by fananchong** [comment]
you fix it directly
