### ISSUE TITLE
UE4 navmesh is generated inside of geometry

### ISSUE THREAD

**Issue by Pierdek** [recastnavigation/recastnavigation#340]
Hi,
I;m trying to undestand and solve an issue that occured in my project in the Unreal Engine 4.17, short story the navmesh is generating inside geometry and I want rid of it.

[https://postimg.cc/image/85a867huz](url)

The UE4 is using pretty old 1.4 Recast & Detour.

The UE4 devs stated that this is a problem within the Recast and We should live with it ;)

https://answers.unrealengine.com/questions/551109/bug-navmesh-generates-inside-blocking-static-meshe.html

Thanks for advices and help.

**Comment by jakobbotsch** [comment]
There are multiple ways to solve this problem.
One easy way is by playing around with the `minRegionSize` setting, which you can read a little about [here](http://digestingduck.blogspot.com/2009/08/recast-settings-uncovered.html). This is typically not very easy to use, and in some cases does not work as you want. For example, when a polygon is at the border of a tile, Recast cannot know whether the total area of the region will be too small, so a small region straddling a polygon will not be removed.

A second easy way to solve the problem is by using a flood-fill algorithm starting from some seed points. The flood-fill should then mark all reachable polygons as walkable, and all unreachable as unwalkable. The demo contains sample code that implements this [here](https://github.com/recastnavigation/recastnavigation/blob/05b2b8da80037887d3e79af8a59a8f0f8ed02602/RecastDemo/Source/NavMeshPruneTool.cpp#L133).

A third much more difficult, but also more flexible way, is by using so-called connectivity data structures. If your mesh does not change at runtime, it is rather simple to build a data structure that keeps track of which polygons can reach which other polygons. This can be used at runtime to filter which polygons should be picked in various situations, for instance when you want to find a polygon that an agent can navigate to for sure. This is the approach I have used previously, and it is on my to-do list to add support to Detour for building and using these.
Note that if you want to efficiently make dynamic changes to the mesh at runtime, then the problem is much harder. In fact if you want to support dynamic one-way jump links then it is conjectured that no efficient data structure exists. If you don't need one-way jump links then you can search for "dynamic connectivity" -- it is a well studied problem.

**Comment by Pierdek** [comment]
Hi @jakobbotsch 
I made some tests around 2) and it is really promising:)  but I have another question:
Is there a nice way to remove unreachable polygon from the tile ?

**Comment by jakobbotsch** [comment]
There is no built-in way to remove polygons completely from the mesh (i.e. remove a polygon and all its underlying data). However you can use `dtNavMesh::storeTileState` to save the correct state after running your flood-fill. Then later you can use `dtNavMesh::restoreTileState to restore the correct state. That way you will not need to redo the flood-fill each time tiles are loaded.

**Comment by flahbak** [comment]
As no built-in technique exists. You can implement signed heightfields which were constructed specifically for that - https://mooncat.dev/navmesh/signed-heightfield/

**Comment by GlassBeaver** [comment]
> As no built-in technique exists, you can implement signed heightfields which were constructed specifically for that - https://mooncat.dev/navmesh/signed-heightfield/

Nice, but won't that wipe out any and all overlapping navmesh polys? In other words you can only have a single Z-layer of navmesh if that makes sense. Which is great for certain RTS games etc. - not so much for games with more verticality.

**Comment by flahbak** [comment]
@GlassBeaver multiple layers of navmesh are supported. It might be hard to see in the pictures but assuming we have "closed" meshes, if you cut out only insides then it should not impact other meshes that are highier/lower.

**Comment by GlassBeaver** [comment]
@flahbak interesting - do you have a project with source code, or is the source code available for purchase?

**Comment by flahbak** [comment]
@GlassBeaver i've reached to you via social networks (fb, li) for more personal chit chat ; )

**Comment by leyleyzhou** [comment]
@flahbak interesting  too.can i get this code from you
