### ISSUE TITLE
Bad navmesh generation in tight area

### ISSUE THREAD

**Issue by cfuzier** [recastnavigation/recastnavigation#351]
When I run RecastDemo in Solo Mesh mode with attached obj file as input mesh, if I build the navmesh with all the default parameter values, it looks correct. If I change the rasterization cell size to 0.10 and build again, then a huge peak appears in the navmesh. Is this a Recast bug?
I've tried to debug and the problem seems to come from getHeight in buildPolyDetail in RecastMeshDetail.cpp, but I don't know how to fix it properly. Any suggestion?
Thank you in advance.

[TTNG_GM_2.zip](https://github.com/recastnavigation/recastnavigation/files/2434820/TTNG_GM_2.zip)

**Comment by cfuzier** [comment]
In buildPolyDetail, at the first call to getHeight, if I replace
getHeight(pos[0],pos[1],pos[2], cs, ics, chf.ch, heightSearchRadius, hp)
with
getHeight(pos[0],pos[1],pos[2], cs, ics, chf.ch, heightSearchRadius*5, hp)
then the problem disappears.
heightSearchRadius seems to be too small but why? It is set to rcMax(1, (int)ceilf(mesh.maxEdgeError)) in rcBuildPolyMeshDetail.

**Comment by jakobbotsch** [comment]
I have tried your input object file and it does not appear to produce any mesh at all (no polygons because the sliver is too thin compared to the agent radius). What are the exact settings you used?

The search radius is used because contour simplification will introduce some slight error into the navmesh. This may cause the detail mesh building to sample heights outside of the heightfield -- to recover, we simply find the nearest height. The idea is that the max error introduced is `maxEdgeError`, so we should always find a height within this radius, but you appear to have found a situation where that is not true.

**Comment by cfuzier** [comment]
Thank you for having a look at this. Here are the settings I used and the result I get.

![image](https://user-images.githubusercontent.com/38348956/46463793-0b7c9980-c7c5-11e8-8a71-9d29beb32c9b.png)

**Comment by cfuzier** [comment]
And here is the BVTree if that helps. It looks strange around the peak.

![image](https://user-images.githubusercontent.com/38348956/46463891-58f90680-c7c5-11e8-9cc3-9c0a6655f28a.png)

**Comment by jakobbotsch** [comment]
I am still not able to produce your screenshot -- have you commented out/removed the `rcErodeWalkableArea` call around line 510 in Sample_SoloMesh.cpp?

**Comment by jakobbotsch** [comment]
I am able to reproduce it after removing the `rcErodeWalkableArea` call. It looks like something goes wrong in contour simplification:

![image](https://user-images.githubusercontent.com/7887810/46472271-f7dd2d00-c7dc-11e8-9e97-00d152f7b460.png)

That contour on the left hand side looks very strange. And indeed, it is no wonder that it fails to sample heights here:
![image](https://user-images.githubusercontent.com/7887810/46472340-28bd6200-c7dd-11e8-9a12-f4b953dddbc9.png)

Unfortunately I am a bit strapped for time at the moment, but I will try to see if I can take a closer look in the weekend or next time.

**Comment by jakobbotsch** [comment]
I took a closer look. It turns out there is a built in limit on the number of iterations Recast will use to walk contours:
https://github.com/recastnavigation/recastnavigation/blob/05b2b8da80037887d3e79af8a59a8f0f8ed02602/Recast/Source/RecastContour.cpp#L119

Your example runs into this limit. If the limit is increased, the problem disappears.
@memononen what is the reason for this limit? Have you run into infinite loops without it?

**Comment by cfuzier** [comment]
Excellent! This fix is OK for me! I just have one additional question: when building the navmesh with the limit increased, everything looks fine except this area:

![image](https://user-images.githubusercontent.com/38348956/46537720-44df0300-c8b2-11e8-8876-3eb02a3c360c.png)

Do you know what happens here? Maybe this is just a display problem because I manage to move an agent through this "hole".

**Comment by jakobbotsch** [comment]
Indeed, that's just a display problem. It is easier to see that there is proper detail mesh there if you just select "Poly Mesh Detail" in the bottom right.

**Comment by memononen** [comment]
@jakobbotsch I've just had a habit of adding some kind of hard termination limit for this kind of algorithms. 

I'm sure you can add a little counter to find real upper limit over here (and pass it to contour walking):
https://github.com/recastnavigation/recastnavigation/blob/05b2b8da80037887d3e79af8a59a8f0f8ed02602/Recast/Source/RecastContour.cpp#L870

**Comment by cfuzier** [comment]
OK, so I will just increase the limit properly. Thank you for your help!

**Comment by jakobbotsch** [comment]
I just wonder whether the limit is necessary at all, since it seems it should produce correctness issues anytime it is hit. So we can probably get by with removing the limit, although I need to take a closer look first.
