### ISSUE TITLE
TileLayers within the same tile don't connect ?

### ISSUE THREAD

**Issue by MINIONBOTS** [recastnavigation/recastnavigation#371]
I have an odd issue that I've never faced before, since most (if not all?) around here just place the built tile mesh into the layer 0. But I'm using a fixed 3d raster for all other things and therefore split also the recast mesh into a 3d raster ( like a lot of cubes ). I'm building the input geometry of each 'box' and then place that build mesh tile into the navmesh the usual way ( m_navMesh->addTile(..) ). On the horizontal axis it connects fine ( I'm extending the rcConfig.width and height by 2*borderSize ), but for the 'up' axis, there is no such value for me to modify, which results in a gap inbetween two meshparts that are within the same tile x-z axis, but on a different layer.

When I extend the min/max bounds of the field's AABB on the horizontal axis, it does overlap but recast is unable to find a path from one layer to the other.

( For building the tiles, I'm already feeding in all 27 neighbour-raster-input geometry, so it does have the data to build and bridge the 'gap' on the up-axis)

Any hints where I can look or what I could check ?

**Comment by MINIONBOTS** [comment]
![image](https://user-images.githubusercontent.com/2842405/51748302-48d6a100-20ac-11e9-8856-3616d15380ba.png)

the red marked area is where I made it overlap, recast cannot find a path from the 'lower layer' meshpart to the 'upper layer'.

**Comment by memononen** [comment]
The layer stuff needs axis aligned edges which are tagged in order to
layers connect.

I initially tried to implement the layers based on tiles, just like you
tried, but I ended up running into a lot of issues with the edges between
tiles on top of each other. I cannot remember exactly what, but some
problems were based in contour simplification, and some obscure ones were
based on the voxelization origo being different.

There are some blog posts from the time I implemented the layers:
http://digestingduck.blogspot.com/search?q=layers

Currently the layers are tied closely to the implementation of the tile
cache.

--mikko

**Comment by MINIONBOTS** [comment]
Thank you for the answer. 
I read through your post and I do understand the reasons why you made it the way it is right now ( a single big 'column' containing the different layers ). I used the layercache in the past, but the lack of the details mesh caused often issues in the navigation logic (2d vs 3d..), especially when I would expand the tilesize even more as you can see on the ss above. So right now I went with monotone partitioning..at the drawback of not having the obstacles available :/...

Before I resign and rewrite my code, you said that the input geometry has to align with the layer edges, I could try to clamp the input geom that crosses the tile boarder to the top/bottom edges of the layer, would that maybe work?

**Comment by memononen** [comment]
I think I was unclear on few things, so let me explain the problem with building navmesh as 3D tiles.

In order to build a 3D tile, say 20x20x20m, we'd need to expand the build area by the agent size, so that an obstacles around the tile are taken care correct. For example you could have a platform at the top of a tile, and another platform at the bottom of the tile above. In that case the agent could not stand on the top platform. For that reason we need the extra data.

As you have noticed, it's not too complicated to build this navmesh. The next problem is to identify the edges of the navmesh that connect to neighbour 3D tiles. Laterally it is simple, since the navmesh is 2.5D and the edges are axis aligned. It also makes it possible to make the connecting a little sloppy, in case the edge is not exactly the same on neighbour navmesh tiles. The reason discrepancies this happen at times is because of floating point accuracy.

Connecting the tiles above and below gets trickier. The edges are very often diagonal, as in your example too. Errors happen, and it is not possible to sloppily connect the diagonals, since that would not result convex polygons anymore. I think I also had issues with terrains, where the 3D tiles would create a lot of small triangles. Anyways, I could not figure out a way to make the system reliable, either by making it deterministic, or to make it able to deal with slightly off data. CryEngine has 3D tile based navmesh generator, but last time I checked it (years ago), it had the same problems I tried to work out. I.e. it would fail a diagonal staircase it certain angles.

So, when I was working on the tile cache, I wanted to have very local changes in the navmesh, so that I would not need to update a whole column of data when something changed. I first looked at 3D tiles, but I could not make them reliable.  I decided that instead of 3D tiles, I try to partition a column of data in layers that do not overlap in 3D. It was reasonably simple to do using monotone partitioning. And that naturally led to axis aligned connections between layers too.

Tilecache tiles were meant to be so small that you would not generally need details. I think it would be far simpler to add detail mesh to tile cache than try to make the 3D tile generation to work.

**Comment by MINIONBOTS** [comment]
Hello Mikko,

the agent fitting into a layer on the Y axis, that is indeed a case I had not considered at all... 
This really makes it hard for me now, seems I have to rewrite the whole logic to use columns instead of boxes, which again conflicts with the other stuff I had build into it...octree for a 3D mesh ontop of the floor mesh, completely free peaceable mesh connections between everything...it could have been so easy if it would just work :)

I had a look at the dtBuildTileCacheLayer on how to add the detail mesh, I fear this is a bit beyond my understanding of the recast internals, the CompactHeightfield data is afaik needed to (re-)build the tile from what I see, but this would mean that this data has to be saved and held in the dtTileCacheLayer, ...or maybe this 'data' is already in the dtTileCacheLayer.heights ? Sadly I don't understand everything in that building process...

Anyway, thank you, I appreciate your help!
