### ISSUE TITLE
Indexes

### ISSUE THREAD

**Issue by alexzk1** [recastnavigation/recastnavigation#379]
![image](https://user-images.githubusercontent.com/4589845/53089152-6b75a180-3514-11e9-894f-c03adede893e.png)

Ok, well, I started to redo this code to use std::vector with boost pooled allocator (i.e. replacing rcNew/delete)..but that's not a point.

I had weird crush in pool. Very rare. So I tried to replace operator [] by call to .at() which does index checks. And I got out of bounds access. I think it comes from original source and remains uncought there.
See screen.

**Comment by alexzk1** [comment]
I did 2 changes, which allow to go, however not sure it it's correct ...bcs not sure logic overall.
1 - IF changed:
```
if (!previd && rid < sweeps.size())
                {
                    previd = rid++;
                    auto& ref = sweeps.at(previd);
                    ref.rid = previd;
                    ref.ns = 0;
                    ref.nei = 0;
                }
```
2nd is below loop changed:
```
// Create unique ID.
        for (size_t i = 1, sz = std::min<size_t>(rid, sweeps.size()); i < sz; ++i)
```

**Comment by jackpoz** [comment]
you could run Recast without any of your custom modifications with Address Sanitizer and see if it finds anything.
chances are your code added the bug.

**Comment by alexzk1** [comment]
Point is, I fix old opensource (2012 around stopped develop) and recast part there was never working actually. Even when I just updated recast to newest, it was all broken yet.
With my fixes it started to do something so I can't just remove it. And many your solutions there I consider too old as well. Must be redone. Most killing feature (my personal opinion) is allocating structures without issuing constructors - such a code should be never exists if it claims C++.

**Comment by jakobbotsch** [comment]
Recast and Detour already expose a pluggable memory allocator. It should be possible to plug your pool allocator in without making any changes to the source.

With regards to this issue it will be hard to tell what is wrong without an example to reproduce it. I am also not very familiar with this part of the code which makes it harder for me to tell.

**Comment by alexzk1** [comment]
Maybe just add bounds checking asserts for now everywhere, so you can see errors later and not just ignore it. Because in current code you will never see any errors most likely.

**Comment by jakobbotsch** [comment]
Adding asserts is reasonable.
> About "pluggable". Not so simple, boost top level interface wants sizes for templates. I.e. `alloc<SomeClass>` which makes it hardly compatible with your current size as parameter. Also boost style is safer because compiler tracks errors.

Generally, Recast and Detour does allocation up-front and does not allocate lots of small instances. Recast and Detour probably has different design goals than you expect. It includes running on consoles and in many other environments where you may want to have a high degree of control over when and how memory is allocated. Writing a small arena or pool allocator that can be plugged into R&D should not be difficult, even if Boost's does not directly fit.

> Also your code is mix of C and C++ which takes worse from both worlds.

These are your opinions and the authors of this library do not share them. It has often been regretted that the library was written in C++ instead of plain C. After maintaining this library for a few years I am inclined to agree as this choice has seemed to attract a lot of bikeshedding wrt. constructors and allocation.

**Comment by alexzk1** [comment]
C++ is just times easier to track errors. And most important, to not do it at all. 
As for consoles...arguable. I program arduino using modern C++, templates, etc. With proper compiler flags code is exactly same speed/size as pure C. But much easier for human.
Today G++ is smarter then 99% of programmers in fact.
