### ISSUE TITLE
Recast/Detour dynamic objects

### ISSUE THREAD

**Issue by killerwife** [recastnavigation/recastnavigation#457]
Hey, I wanted to ask about something. I require certain tiles to have meshes that can be turned off. The maximum I need is 49 per tile. What is the best course of action with best possible performance. Currently the inclusion mask / exclusion mask is 16 bits. Would it be a too big of a performance hit to upgrade that to a 64-bit mask in 2020?

Or what are good other alternatives to temporarily turned off meshes. I heard there are some temporary obstacles possible, however I read that they had some upper limit on complexity. Is there a simple function to which we can supply vertices that would then compute what to disable? Thanks for any pointers really. I have a successful prototype that extracts the obstacle as a separate mesh flag and supplies proper flag if it is turned on.

**Comment by AndrasMumm** [comment]
What kind of meshes/obstacles are these? Are they obstacles like doors, walls, etc., or are they actually full sub meshes that are walkable, like bridges, etc.

If they are actually dynamic obstacles, then the dynamic obstacle handling of the DetourTileCache is a solid solution.
However, I am unsure if it works if you want to add walkable grounds. I think it is primarily designed to handle obstacles that need to be fully avoided.

If it is walkable ground (which I assume based on your phrasing) that you want to enable or disable freely (like you do not want to add an obstacle, but rather some bridge is only enabled sometimes, etc. this kind of stuff), then if it exceeds the current 16-bit mask, a possible (but not particularly clean) solution is using the DetourNavMesh::setPolyFlags function to dynamically set or take away the ability to walk on the polygons of the sub meshes.

You could determine the polygons in the navigation mesh that correspond to the sub meshes that you want to be able to disable or enable using a simple "Take all polygons inside a boundary box" approach and then saving it.
That way performance-wise it should be pretty quick to disable or enable the given polygons.

Be careful however if you are already using the dynamic obstacle handling with the DetourTileCache, this approach won't work since polygon references are not guaranteed to stay the same after a rebuild of the navmesh.

**Comment by killerwife** [comment]
I am aware. My case is that mesh regeneration doesnt seem like a viable option due to the sheer stress it would put on the server. The current requirement is to implement multi tile structures that when spawned into the game world, not only require to block movement beneath them but also enable pathing on them. This can range from something simple as a large vehicular door which has side posts to walk on, to something gargantuan as a dynamic boss platform.

So far my prototype seems to take care of toggling using areas / polyflags, however I do not know how to nicely generate the area beneath them. I.e. there are two areas, one beneath, which is on when object is not there, and the other, when the object is there. As of right now I do not know a straightforward way how to segment that during mesh generation.

During mesh generation I ofc have access to the object polys. 63 areas and the dynamic flag changing should not be too impactful. The idea is for the meshes and tiles to be static and only the flags would change. If you have an idea how to geometrically segment out the mesh below the given object into a designated area, it would be appreciated :)

**Comment by AndrasMumm** [comment]
That would be really hard to accomplish. After thinking about it for a bit, I could not come up with a solution.
There are several things I would see being pretty hard to manage properly:
- Polygon connections. If you have these obstacles, some polygon borders might need to connect to different polygons based on which "version" of the mesh you want. I think this is the biggest issue.
It is impossible to have the polygons on top of your obstacles connected with the polygons that, with the obstacles deactivated, connect to the polygons under your obstacle.
- Eroding the walkable area around the activated obstacles. This is more than just activating and deactivating some polygons around the obstacle.
- Lots of edge cases.

Recast/Detour out of the box, sadly, does not support what you need.
The TileCache won't allow for complex geometry for performance reasons.
(see https://github.com/recastnavigation/recastnavigation/issues/6#issuecomment-25472458)

The easiest solution would be rebuilding the full tile upon activation or deactivation of a sub mesh, but that is a big performance hit that you probably cannot tolerate.
I don't think it is really possible to achieve your wanted behavior with Recast/Detour.
Maybe somebody else can give you another hint in a good direction.

Best of luck!
