### ISSUE TITLE
How do I get the coordinates away from the wall?

### ISSUE THREAD

**Issue by wojiaoz71** [recastnavigation/recastnavigation#458]

**Comment by AndrasMumm** [comment]
You need to include a bit more information so your question can be properly understood.
I assume your problem is that the generated navigation mesh is too close to the wall/to obstacles.
If you are using the RecastDemo or your code is really close to the RecastDemo then you need to increase the agentRadius in the BuildSettings object. In RecastDemo that is doable over the user interface.
https://github.com/recastnavigation/recastnavigation/blob/9337e124182697de93acb656ef25766486738807/RecastDemo/Include/InputGeom.h#L42-L43

This variable is used to set walkableRadius of the rcConfig object used for the generation 
https://github.com/recastnavigation/recastnavigation/blob/9337e124182697de93acb656ef25766486738807/RecastDemo/Source/Sample_TileMesh.cpp#L820

which in turn is used as the parameter to rcErodeWalkableArea
https://github.com/recastnavigation/recastnavigation/blob/9337e124182697de93acb656ef25766486738807/RecastDemo/Source/Sample_TileMesh.cpp#L959-L960

rcErodeWalkableArea is the function that marks the areas around obstacles(so including walls) in the heightfield so that the resulting navigation mesh leaves enough space for an agent with the given radius to move around the obstacles.

If you use Recast in your own project what matters in the end is the value you give to rcErodeWalkableArea

**Comment by wojiaoz71** [comment]
Thank you

**Comment by wojiaoz71** [comment]
I use findStraightPath get Path,but the coordinates are close to the wall.I want to keep these coordinates away from the wall.

**Comment by AndrasMumm** [comment]
You need to specify the agent range in the generation of the navigation mesh.
If the area too close to the wall is already part of the navigation mesh, Detour can and will use these polygons.

If you generate the navigation mesh with a proper agent radius and call rcErodeWalkableArea as demonstrated in the RecastDemo the "coordinates" close to the wall will not be part of the resulting navigation mesh and the path generated by findStraightPath will not be close to the wall
