### ISSUE TITLE
Differences between dtNavMesh and dtTileCache?

### ISSUE THREAD

**Issue by setzer22** [recastnavigation/recastnavigation#464]
Hi, and sorry to post a question as an issue. If there's a better channel for this please let me know!

From the description of dtNavMesh, I see it's "a navigation mesh based on tiles of convex polygons". Now, what's the difference between this and a dtTileCache? The fact that there is no documentation for dtTileCache confuses me, is it an internal implementation thing?

In my project, I'm interested in having dynamic obstacles, and the addObstacle method only seems to only be present in dtTileCache. So how does this work? Are they the same thing, does one own or provide access to the other, or are they just two separate constructs. That is:

- Should skip building a dtNavMesh entirely and just replace it with a dtTileCache for my project?
- Should I just build a dtNavMesh, and get access to methods like addObstacle somehow?
- Should I have both a dtNavMesh and a dtTileCache?

I'm also interested to know if there's a writeup with a high-level overview of the library somewhere that would solve this kind of questions.

Many thanks for the hard work on this! :)

**Comment by powof2** [comment]
As far as i know, you need to use 'temp Obstacle' tool in recastDemo to build your navmesh and tilecache.
then call dtTileCache->update(timeDelta) every frame (or every few frames) in your game to get your internal navmesh re-build if you add/remove obstacles on the fly.

**Comment by Bromeon** [comment]
I also found two old blog articles which give a tiny amount of context around tile caches:

http://digestingduck.blogspot.com/2011/01/temporary-obstacle-progress.html
> So the stuff I have working now is a preprocess step which rasterizes the tiles, creates a minimal representation of the heightfield and then "zips" it. These data chunks are stored in tile cache. Upon request tile cache will create a piece of navmesh for you which includes all the temporary obstacles too.

http://digestingduck.blogspot.com/2011/01/2d-grids-for-win.html
> And I implemented a tile cache, which basically stores that layered heightfield in compressed form and uses it to kickstart a navmesh generation process. In case you just wanted to mark some areas impassable, that method speeds up the tile generation process my almost a magnitude.

**Comment by powof2** [comment]
if i am correct:
- Solo Mesh tool will create one single piece of static navmesh (that's why 'solo', i guess)
- Tile Mesh tool will create navmesh in tiles (grids), so you can streaming in or out while player walking around
- Temp Obstacle tool will create tiled navmeshes and tiled cache together, so you can add/remove runtime obstacles, why it is in tile (or grids)? because its much faster to build one single tile than the whole.

**Comment by Jadd** [comment]
DtNavMesh and DtTileCache are not the same thing.

A navmesh is a collection of mesh tiles. To clarify what @powof2 mentioned, a "solo" navmesh is simply a tiled navmesh containing only one tile. The number of tiles you should use entirely depends on the size and complexity of the geometry (and therefore the resulting mesh.)

Temporary obstacles will require some additional intermediate data in order to quickly rebuild the tiles "touched" by the obstacle - ie. any tiles that lie within the obstacle's bounds. This functionality is provided in dtTileCache, which contains the dtCompressedTile list (the intermediate data) and copies the rebuilt tiles into the dtNavMesh instance.

> Should skip building a dtNavMesh entirely and just replace it with a dtTileCache for my project?

If you need obstacles, yes, use dtTileCache. But you'll still need a baseline dtNavMesh for the tile cache to update.

**Comment by setzer22** [comment]
Many thanks for the explanation @Jadd! 

Just to clarify then: I need to obtain a dtNavMesh with my base geometry, and then build a dtTileCache out of it, right?

Could you please point me to some example usage for dtTileCache? That would be extremely helpful! :smile:

**Comment by Jadd** [comment]
To clarify, a navmesh and a tile cache can be built independently. But a tile cache generally isn't much use without a navmesh to update into.

You can see a tile cache and navmesh being built from the input geometry in Sample_TempObstacles::handleBuild(). That is your best example.

**Comment by memononen** [comment]
The tile cache stores "half baked" voxels to which can be used to quickly rebuild navmesh. That way it allows you to paint areas (ie. obstacles) in to the navmesh and rebuild the required tiles. So you first build the tile cache and then use it to make the navmesh. If you wish you can store both on disk, or you can just store the tile cache and ask it to update the tiles at load (it's not free).
