### ISSUE TITLE
dtNavMeshQuery::findRandomPoint got failed sometimes

### ISSUE THREAD

**Issue by EfveZombie** [recastnavigation/recastnavigation#556]
https://github.com/recastnavigation/recastnavigation/blob/314e94b692fe6c5df1de703527c8774a473526b7/Detour/Source/DetourNavMeshQuery.cpp#L301-L307

In some case, the `pt` calculated by `dtRandomPointInConvexPoly` would be exactly at right edge (+x) of this poly, e.g:
![image](https://user-images.githubusercontent.com/34877029/195102664-d4630af7-5ff1-4ce9-bcc5-4a19249e7c68.png)
And it failed in `getPolyHeight` after, because `dtPointInPolygon` said this point is not in the triangle.

I know the last part is a feature of `dtPointInPolygon`, but it is really weird if I just want a random position and got `DT_INVALID_PARAM`.

**Comment by grahamboree** [comment]
Hmm yeah good catch.  Seems like in every case this is used we want something where none of the barycentric values are exactly 0 or 1.

Moreover though I'm not sure why it needs to check that `getPolyHeight` succeeds immediately after choosing a random point in the triangle.  It appears that it's just checking that `dtRandomPointInConvexPoly` actually worked?  Not sure.  @memononen maybe you recall some edge case here this is handling?

**Comment by EfveZombie** [comment]
Hi, there is a simple fix at #560 . I think if the algorithm of `dtRandomPointInConvexPoly ` is guaranteed, it does not need to check the status of `getPolyHeight`.

**Comment by jakobbotsch** [comment]
As I recall, the problem was that we needed to change `dtClosestHeightPointTriangle` to handle degeneracy which broke the existing implementation of `getPolyHeight` that was based on it. At that time, I believe I convinced myself it makes more sense that `getPolyHeight` is about exact XZ contains check, and `closestPointOnPoly` is the robust one that works.

I think the bugfix here is just going to be to replace `getPolyHeight` with `closestPointOnPoly`. But if you think introducing epsilon in `getPolyHeight` is better, then that seems reasonable to me too.

**Comment by jakobbotsch** [comment]
> It should be as permissive as it can be, imho it should clamp rather than discard.

FWIW, this would make `getPolyHeight` and `closestPointOnPoly` equivalent APIs. That makes sense to me, but of course the `DetourNavMeshQuery` code with the bug above would still need to change to not check the return value.

**Comment by memononen** [comment]
`getPolyHeight()` indeed seems obsolete. And I agree that `closestPointOnPoly()` is the right choice to use in this case.
