### ISSUE TITLE
BUG:height Problem of Sample_TileMesh 

### ISSUE THREAD

**Issue by sherlockxie** [recastnavigation/recastnavigation#594]
using an object with two cube exported as obj file from unity .Here is cube status: 
Cube A size is (50,0.1,50), Position is (0,0,0)
Cube B size is(10,0.1,10), Positon is (0,4000,0)
using sample_TileMesh case to build navMesh ,that is how it look like this 
![image](https://user-images.githubusercontent.com/20817640/208051609-95d9da07-1b15-4242-a024-cef8569c1529.png)

**Comment by grahamboree** [comment]
I'm not really sure I fully understand the issue you're facing.  Could you upload the obj file and list the recast settings you're using, as well as the expected outcome?

**Comment by sherlockxie** [comment]
[Cube.zip](https://github.com/recastnavigation/recastnavigation/files/10292269/Cube.zip)
@grahamboree  Sure, recast setting is the default value of the tileMesh Sample.

**Comment by grahamboree** [comment]
Thanks for the additional info!  It looks like you're hitting the maximum heghtfield y-dimension, which is clamping the top triangles to the maximum.  The maximum size of the rasterization heightfield along the y axis is defined here https://github.com/recastnavigation/recastnavigation/blob/b51925bb8720e78a65c77339a532459b96ddfc7e/Recast/Include/Recast.h#L269

This is happening because you have geometry that spans about 4040 units and the default cell height for the heightfield is 0.2.  The heightfield would need to be `4040 / .2 = 20200` cells high, but the maximum size it can be is 8191 cells high.  Because triangles are outside the maximum size, they get clamped to the maximum height in rasterization, which results in the navmesh for cube A halfway between cube A and B.

This definitely could use better error signaling, and I'm not sure that clamping triangles like this (as opposed to discarding them) is the correct choice here, but nevertheless...

To work around this you can either increase the cellSize parameter, re-scale your geometry prior to sending it to Recast, or bake separate navmeshes for each cube.  Hope this helps!

**Comment by sherlockxie** [comment]
@grahamboree thx a lot! It works! :D
