### ISSUE TITLE
InputGeom::intersectSegmentTriangle only works from one direction

### ISSUE THREAD

**Issue by astutejoe** [recastnavigation/recastnavigation#603]
Hello there!

I was cracking my head here trying to understand why one of my InputGeom::raycastMesh queries was returning false even though the segment and the triangle were clearly intersecting. It seems to be because the InputGeom::intersectSegmentTriangle implementation seems to be following the "Intersecting Ray or Segment Against Triangle" chapter section from the "Real-Time Collision Detection" book by Christer Ericson, the issue seems to stem from that a segment has no direction, a ray does, and even though our function is named intersectSegmentTriangle it seems is to only work on a specific triangle winding and ray direction. Test data:

```
sp = 27938.0000, -5453.00000, -25048.0000
sq = 27922.0000, -4574.00000, -25148.0000
a = 27828.353516, -4585.178223, -25283.853516,
b = 27927.289062, -4585.178223, -24941.593750
c = 27927.289062, -4585.178223, -25283.857422
```

This will return false (no intersection), but if you switch sq with sp, now it returns an intersection. I'm not too sure how to tackle this one honestly, maybe a different algorithm? Test both directions of the ray? I'm happy to PR a solution if we can agree on one. It's important to note raycastMesh is not used for navmesh generation, it's only being used for debugging in the repo.

**Comment by grahamboree** [comment]
Hi!  Super appreciate you finding this and even where the original code was likely adapted from!  Certainly makes my life easier :)

I suspect that much of this code (and the code in RecastDemo more generally) has some latent issues like this.  This demo project was created mostly to showcase features of Recast and Detour so it's likely somewhat buggy and probably relies on a number of opengl-specific things like triangle winding order.  It wasn't really meant to be part of Recast itself when it was written.

That being said, I still think it's important that this code is robust and doesn't mislead people with weird issues like this since it is part of the repo, so it's definitely worth fixing.  Will add this to my todo list, but If you're so inclined a PR would be greatly appreciated. 😉 Thanks again.

**Comment by astutejoe** [comment]
@grahamboree That's great to hear! I can cook a PR, just one thing, is it okay if I submit the code with more than two letters in variable names hehe? I already fixed this problem locally but with descriptive variable names, which won't quite fit the surrounding code style.

**Comment by astutejoe** [comment]
Also, since then I realized there's two additional problems:
[dtIntersectSegSeg2](https://github.com/recastnavigation/recastnavigation/blob/main/Detour/Source/DetourCommon.cpp#L373)  is actually doing line vs line intersection, not segment vs segment, leading to some really odd string pulled paths sometimes, Unreal fixed this already:
https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Source/Runtime/Navmesh/Private/Detour/DetourCommon.cpp#L501

**Comment by grahamboree** [comment]
Please! 🙏  It's been my personal mission to try to improve all 1 and 2 letter variables with more descriptive names, but since I'm trying really hard not to break things in the process it's been slow going.  I've also been focused on the core library rather than the demo project so far.

The other issue is probably worth a separate PR just to keep things organized if you're inclined to tackle that as well.  Again, thanks for bringing up these bugs and for being open to writing PRs to fix them!

**Comment by astutejoe** [comment]
Sounds good @grahamboree! I'll try cooking some PRs tonight, worst case, this weekend. Another one I'm considering is this one: 
https://groups.google.com/g/recastnavigation/c/m_JMXgmlIs4

Would you have any clues? Why we don't use y? My only guess is that point in convex hull algorithms aren't easy to implement and this is close enough?
