### ISSUE TITLE
New release tag?

### ISSUE THREAD

**Issue by hadean-johnm** [recastnavigation/recastnavigation#629]
There hasn't been a tagged release since 1.5.1 in February 2016.  

I saw that there is a `release-2.0` branch but no 2.0.0 release tag. Would I be right in guessing that branch is in a pre-release state or can commit `67c36bda750f36b2b4152db57a23170ed7a0683c` be considered for a 2.0.0 tag?

**Comment by grahamboree** [comment]
Hi!  Yes, unfortunately we haven't had an official tagged release in a while, though there's been some consistent fixes that have gone in since the last one and folks like Godot are just integrating the latest from main.  That being said, it's likely time for a new release.

The reason we have a 2.0 branch is because there are a number of breaking changes we received in pull requests that we thought were worth accepting, but were worried about breaking backcompat for folks.  That was a few years ago and it doesn't make much sense to have those changes languish in a dev branch forever.

Thanks for bringing this up, I'll put together a new official release soon.

**Comment by grahamboree** [comment]
Created an official [v1.6.0 release](https://github.com/recastnavigation/recastnavigation/releases/tag/v1.6.0)!  I'm going to move the 2.0 changes into main and set that as a v2.0 WIP alpha version.
