### ISSUE TITLE
Triangles looks strange. 

### ISSUE THREAD

**Issue by sherlockxie** [recastnavigation/recastnavigation#668]
![image](https://github.com/recastnavigation/recastnavigation/assets/20817640/43789b20-7c94-4059-9a71-ed3f3757bc00)
When I tried to use detailTriangles in tiles to show the navMesh render zone,it looks strange with lots of small triangle in the specific part,is that normal?

**Comment by sherlockxie** [comment]
Even though I used a regular plane consist by lots of square to bake navmesh,the rendered detailMesh shows that triangle still no rule in my sight.
![image](https://github.com/recastnavigation/recastnavigation/assets/20817640/38205116-f079-44a7-897a-f117d2da0949)

**Comment by grahamboree** [comment]
Hi!  Can you provide more context or an obj to repro the issue here?  It's really hard to tell from your images what's happening.  

In general Recasts' triangulation system favors the largest triangles possible, so you may see it generate large triangles in large areas and smaller triangles in fine details around obstacles.
